// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihaxrjstmeacimegpfuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloYXhyanN0bWVhY2ltZWdwZnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTkzODksImV4cCI6MjA2NTI5NTM4OX0.2kZ46J9rMTpD4KCp-ahC-iAZfjfD1CVkr-z9moXsS40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);